### ISSUE TITLE
크롤링을 이용한 chrome extension 제작 문의

### ISSUE THREAD

**Issue by kimud6003** [brave-people/Dev-Event#143]
**안녕하세요, Dev-Event를 통해 많은 소식을 접할수 있게 해주셔서 감사합니다!**

다름이 아니라 컴퍼런스나 대회를 참여하기 위해, 학생으로서 자주 확인하러 해당 레포지토리를 확인합니다.
지금은 어플도 있어서 편의성에서 많이 좋아 졌지만, 브라우저 google chrome extension을 통해서 이번달에 있는 일정을 확인하면 편할거 같다는 생각이 들었습니다.
그래서  부족한 실력이지만 해당 문서의 내용을 extension으로 만들고자 하는데 괜찮을지 여쭤보고 싶습니다

**Comment by KoEonYack** [comment]
@kimud6003 님 안녕하세요. 

용감한 친구들 디렉터 고언약입니다. 

좋은 제안 감사합니다.

작년에 1.0 데브 이벤트 반응형 웹 버전을 공개하였으며 웨일 확장앱으로 공개하였습니다. 두 달의 기간동안 500명 정도 다운받으셨던것으로 기억합니다.

텍스트 기반 README로 개발자 행사를 보여주는데 한계를 느끼어 행사 이미지를 보여주는 Web으로 전환예정입니다. 당초 계획대로라면 지금쯤 개발이 완료되어야하나 작업하는 분들이 현업분들이라 쉽지 않네요^^ 목표는 내년 초에는 Web을 공개하여  README로 행사 안내를 종료할 것입니다.

만약 작업하신다면 반년 이내로 크롬 확장앱 서비스를 할 수 없다는 슬픈(?) 각오를 하셔야겠습니다.

서론이 길었습니다.

혹시 어떤 방식으로 기획하시는지 알 수 있을까요~? 단순 크롤링하여 한달 행사를 보여주는것일까요?

**Comment by softpeanut** [comment]
#### 안녕하세요 저는 현재 고등학교에 재학중인 학생입니다 😀
용감한 친구들에서 제공해주는 대회 또는 컨퍼런스에 대한 정보를 받아서 프로젝트를 진행하고 싶은데 혹시 단순 크롤링으로 행사를 보여주는 용도로 사용한다면 괜찮을까요? 매주 이슈가 생성되면 그때마다 정보를 받아오려고 합니다 !

**Comment by kimud6003** [comment]
@KoEonYack 님 빠른 답변 감사합니다!

현재 해당 Web을 만들고 있었는지 몰랐습니다 😱.

익스텐션은 간단하게 크롤링 한 정보를 PoPup을 통해 간단히 현재 지원 가능한 이벤트를 보여줍니다.

또한 현재 지원 가능한 이벤트에 관심을 체크하면 해당 일정의 마지막 날이 되었을때  push notification을 통해 알려주고자 합니다.

현재 생각하고 있는 디자인은 아래와 같습니다
![스크린샷 2021-11-18 오후 3 22 14](https://user-images.githubusercontent.com/61041800/142363479-c87132a9-5df8-46bb-965e-7130dca909b1.png)

**Comment by KoEonYack** [comment]
@kimud6003  님 확인 감사합니다^^

데브 이벤트를 활용한 하나의 좋은 서비스가 되겠습니다. 

두 가지 제안을 드리려고 합니다. 

제안 1. [용감한 친구들](https://github.com/brave-people) Crew로 초대

> Dev-Event-Web, Dev-Event-Android, Dev-Event-Subscribe 저장소를 개발하시는 분도 용감한 친구들 Crew로 초대하여 함께 서비스를 가꾸어 가고있습니다.

제안 2. 용감한 친구들의 Dev-Event-Chrome-Extention 저장소 이름으로 해당 서비스 개발 및 운영

> 크롤링 서비스의 경우 제가 데브 이벤트 format를 변경한다면 서비스가 죽어버리는 불상사가 발생합니다. 1년간 크게 두번 변경하였습니다. 또한 Web 버전에서는 용감한 친구들 소속 프로젝트라면 크롤링 서비스에서 나아가 API를 통해서 행사 정보를 불러올 수 있게 해드리려고 합니다. API 서버 만든다면 관련해서 미리 사용해볼 수 있게 해당 저장소에 Issue와 Secret Token을 전달해드리려고 합니다. 또한 해당 프로젝트는 Dev-Event 저장소의 상단에 추가하여 서비스를 조금이나마 알려드리겠습니다.

저의 제안에 대해서 코멘트 주세요~

감사합니다^^

**Comment by KoEonYack** [comment]
@softpeanut 님 안녕하세요~

저의 comment를 보시면 아시겠지만 내년 초부터 단계적으로 README로는 더 이상 행사를 제공하지 않을 생각입니다. 

상용 배포 하지 않는 토이 프로젝트일까요~?! 어떠한 성격의 프로젝트인지 궁금합니다 ^^

별도의 issue를 열어드리면 코멘트 드리겠습니다.

**Comment by kimud6003** [comment]
@KoEonYack  님 확인해주셔서 감사합니다!

평소 Dev-Event를 보면서   React-native로 IOS를 만들어본다면, Dev-Contents를 문제를 제출하는 챗봇을 만들어 본다면 좋을거 같다 라는 생각을 혼자 재미있는 상상해보곤 했습니다.  

그래서 저는 첫번째로 제안해주신 Crew 분들과 서비스를 같이 가꾸어 보고싶다는 생각이 들었습니다!

최대한 열심히해서 해당 Extension과 다른 서비스도 만들수 있도록 해보겠습니다.

감사합니다!😀

**Comment by KoEonYack** [comment]
@kimud6003 님 

용감한 친구들 초대메일 보냈습니다.

https://github.com/brave-people/Dev-Event-Chrome-Extention 저장소에서 작업하시면 됩니다.

진행하시다가 궁금한점 있으면 해당 저장소에 이슈 남겨주세요

감사합니다. 👍

**Comment by KoEonYack** [comment]
해당 issue는 닫겠습니다^^

**Comment by osj3474** [comment]
멋진 콜라보가 될거 같아요~~~😆 반갑습니다 ㅎㅎㅎㅎ
