### ISSUE TITLE
토이 프로젝트에 크롤링 활용 문의드립니다 !

### ISSUE THREAD

**Issue by softpeanut** [brave-people/Dev-Event#144]
#### 안녕하세요 현재 고등학교에 재학중인 학생입니다😃
학교 내의 동아리에서 저희 학교를 대상으로 프로젝트를 진행하려고 합니다. 
최종적인 목표는 학교 내에서 실제 서비스를 운영하는 것입니다. 
이 프로젝트에 용감한 친구들에서 제공해주는 대회 및 컨퍼런스 정보를 크롤링해서 사용해도 괜찮을까요?
매주 새로운 Issue가 생성될 때마다 정보를 불러와 사용하려고 합니다 !!

**Comment by KoEonYack** [comment]
@softpeanut 님 안녕하세요^^

> [Github Dev Event](https://github.com/brave-people/Dev-Event)에서 제공하는 정보입니다.

크롤링하여 보여주는 행사 페이지에 위와 같은 문구가 들어간다면 사용 가능합니다! 

이전 issue에 남긴 것처럼 지금처럼 README로 행사 안내는 내년 초중반쯤에는 종료할 예정이라는 것을 염두해 두셔야겠습니다!

홈페이지 나오면 알려주실 수 있으실까요~? 궁금합니다 👍 

Dev Event가 교내 서비스에 도움이 되었으면 합니다.

감사합니다.

**Comment by softpeanut** [comment]
@KoEonYack 답변 감사합니다 !!
일단 크롤링 허용해주셔서 감사합니다 ㅎㅎ 교내 서비스 제작에 많은 도움이 될 것 같습니다 😄😄
추후에 저희 프로젝트가 완료되어서 배포되면 알려드리겠습니다 !
한 가지 궁금한 점은 Dev-Event-Subscribe에서 생성하는 Issue도 종료되는 것인가요?

**Comment by KoEonYack** [comment]
@softpeanut  확인 감사합니다.

우선은 Dev-Event-Subscribe는 제가 작업하는 프로젝트가 아니라서요^^

Dev-Event-Subscribe 또한 크롤링 방식이라 README를 종료한다면 포멧을 변경해서 제공할 수도 있으며 아직 어떠한 것도 정해진 것은 없습니다. 

감사합니다

**Comment by KoEonYack** [comment]
해당 issue는 닫도록 하겠습니다!
즐거운 개발 되세요 👍
