### ISSUE TITLE
mash-up 동아리 링크 오류 문제

### ISSUE THREAD

**Issue by dlswer23** [brave-people/Dev-Event#146]
mash up 동아리에 관심있어 링크를 타고 들어가니 
<img width="1423" alt="스크린샷 2021-11-29 오후 12 10 46" src="https://user-images.githubusercontent.com/66577589/143802928-a7aedde2-06ca-4a84-b491-2ce68567dae9.png">

이 사이트가 뜨는데 제가 아는 mash-up 사이트는 
https://www.mash-up.kr/
이게 맞지 않나요..?

**Comment by KoEonYack** [comment]
@dlswer23 님 issue  감사합니다.

저도 궁금해서 찾아보니 작년 여름에는 .it 도메인을 사용한것으로 보입니다! (참고. [web.archive](https://web.archive.org/web/20210718204836/https://mash-up.it/))

링크는 수정하겠습니다!

감사합니다 👍
