### ISSUE TITLE
Watch시 mail을 보내주는 기능을 이용한 AutoMailing

### ISSUE THREAD

**Issue by Limm-jk** [brave-people/Dev-Event#16]
안녕하세요!! 어제 PR하면서 의견 드렸던 사항을 간단하게 아이디어 검증만 해서 가져와봤습니다.

https://github.com/Limm-jk/event-autoMailing-Demo/issues/3

우선 크롤러를 통해 dev-event 저장소를 크롤링하여서  자동으로 이슈에 올려주는 기능을 만들어보았습니다.
대충 만들어서 별거 없습니다 ㅎㅎ,,,ㅠㅠㅠㅠ

여기에 actions만 붙이면 우선 하루에 한번 꼴로 보내주는 형식의 구현물은 나올 것 같습니다!!

단점은 issue가 많이 쌓이는 것,,,,? 저장소를 따로 운영하는 것이 좋겠네요.

**Comment by KoEonYack** [comment]
@Limm-jk 

궁굼했었는데 빠른 결과!! 감사합니다. :)

event-autoMailing-Demo 저장소에 dev event 따뜻한 말씀 감사합니다 !!

Watch를 한 사람은 Issue가 등록되었을 때 메일을 받을 수 있기에 이런 기능이 가능하군요!

좋은 기능이네요!! 적용하면 좋겠어요!!👍👍

지금 Watch를 누른 분들에게 원하지 않게 메일이 갈 수 있기에 별도의 저장소를 만드는 것이 좋아보여요~! 이슈가 늘어가는 건 문제가 될 부분은 아니겠고요!

지금 크롤링에서 일시(일정의 시작, 마감 포함), 주최까지 들어가면 완벽하겠어요! 이것까지 확인된다면 Dev-Event-Subscribe 저장소를 만들께요!

기능이 확인된다면 Dev-Event 상단에 Dev-Event-Subscribe 저장소에 Watch 누르면 메일이 간다고 홍보를 붙여야겠네요!

좋은 기능 구현해주셔서 감사합니다 :)

**Comment by Limm-jk** [comment]
@KoEonYack 
안녕하세요!! 피드백 정말 감사드립니다.

피드백을 주셨던 방향대로 **output에 주최 및 일자가 모두 반영**되도록 바꿔보았습니다.
마감 일자를 따로 추출한 후에, 현재 날짜와의 비교를 통해 **마감된 행사는 출력이 되지 않는 기능**을 추가해보았습니다.

이런 방식으로 하면  두달치를 보는 것도 좋을 것 같아, 크롤링 범위도 조금 늘려보았습니다.
https://github.com/Limm-jk/event-autoMailing-Demo/issues/17

위의 링크 한번 참고해주시고, 또 다른 생각이 있으시다면 멘션 남겨주세요!

**Comment by KoEonYack** [comment]
@Limm-jk 

Good~ 최고네요!!👍👍 감사합니다 :)

마감된 행사는 출력이 되지 않는 기능까지 완벽하네요!!!

용감한 친구들 그룹 페이지에 `Dev-Event-Subscribe` 저장소를 만들어서 본 저장소를 watch(Issue 등록 알람)한 경우 알람이 받게 하면 좋겠어요!!

매주 일요일 밤, Dev Event 카드뉴스로 단톡방 4곳(약 3700명)에게 개발자 소식을 알려주고 있는데요!!

너무 많은 메일은 구독자들에게 피로도를 줄수기에, 카드 뉴스와 같은 날인 일요일 밤쯤으로, 주 1회 발송은 어떻게 생각하시는지 궁금하네요!

방향에 공감하신다면, `Dev-Event-Subscribe`의 collaborator로 참가해주셔서 주 1회 메일 발송을 해주시며 Dev-Event-Subscribe를 운영해주실 수 있으신지 의견을 살짝 여쭈어봅니다😊😊 

*메일이 어떻게 날라오는지 확인을 위해서 저장소 watch눌러두었어요! 혹시 한번 파이썬 스크립트 돌려주실 수 있으신가요~~!

**Comment by KoEonYack** [comment]
(comment를수정하여 다시 남겨요!)

@Limm-jk 

Good~ 최고네요!!👍👍 감사합니다 :)

마감된 행사는 출력이 되지 않는 기능까지 완벽하네요!!!

용감한 친구들 그룹 페이지에 `Dev-Event-Subscribe` 저장소를 만들어서 본 저장소를 watch(Issue 등록 알람)한 경우 알람이 받게 하면 좋겠어요!!

매주 일요일 밤, Dev Event 카드뉴스로 단톡방 4곳(약 3700명)에게 개발자 소식을 알려주고 있는데요!!

다수의 메일은 구독자들에게 피로도를 줄수기에, 카드 뉴스와 같은 날인 일요일 밤쯤으로, 주 1회 발송으로 생각하고 있습니다~!!

메일이 어떻게 날라오는지 확인을 위해서 저장소 watch눌러두었어요! 혹시 한번 파이썬 스크립트 돌려주실 수 있으신가요~~!

**Comment by Limm-jk** [comment]
지금 이슈가 새로 생성되었습니다!! 한번 확인 가능하실까요?

**Comment by KoEonYack** [comment]
![스크린샷 2021-02-07 오후 6 10 27](https://user-images.githubusercontent.com/28642484/107142056-c312af00-696f-11eb-8f27-e6ebf8a200a0.png)

잘 왔습니다!!! 좋네요!!!! 

Limm-jk님 저장소의 event-autoMailing-Demo를 용감한 친구들 organization에서 지속적으로 발전시켜주실 수 있으실까요?!?! collaborator로 초대해 드리겠습니다 :)
지금 생각하는 발전 포인트는 {크롤링 기준시점 한달 후까지 행사 가져오기, 이슈 상단에 Dev Event이름 및 설명을 남겨줌} 이정도 아닐까 생각해봅니다!!

'Dev-Event-Subscribe' watch누른 분들에게 매주 일요일 메일링 보내는것은 제가 진행하는 방식으로 하는게 어떨까 제안해봅니다!!

더 좋은 방향이 있다면 제안해주세요!!😊😊

**Comment by Limm-jk** [comment]
재미있을 것 같습니다!

권한을 주신다면 Dev-Event-Subscribe repo에 코드를 다시 정리해서 다음 주? 정도부터 서비스를 할 수 있다면 좋겠네요.

Dev Event관련 스크립트를 알려주신다면 이 내용은 바로 추가해두겠습니다.

**Comment by KoEonYack** [comment]
긍정적인 답변 감사합니다 😊

크롤링 스크립트 저장소인 [Dev-Event-Subscribe-Script](https://github.com/brave-people/Dev-Event-Subscribe-Script) 와, issue 등록를 통한 메일링 저장소인 [Dev-Event-Subscribe](https://github.com/brave-people/Dev-Event-Subscribe)에 maintain Role을 드렸습니다!

다음주 정도 서비스 가능하면 좋겠네요! 준비된다면 Dev-Event상단 페이지에 메일링 기능 소개를 추가해야겠어요!

살짝 추가 방안은 이번주 수요일 전까지[Dev-Event-Subscribe-Script](https://github.com/brave-people/Dev-Event-Subscribe-Script)에 issue로 등록해둘께요~!!

앗, 참고로 3월 행사부터는

- __[AI EXPO KOREA 2021](https://event-us.kr/zvKlsXnNkKW6/event/26657)__
  - 분류: `온라인`, `컨퍼런스`, `.NET`
  - 주최: 서울에쎄
  - 일시: 03. 24(수) 10:00 ~ 03. 26(금) 17:00

요런 포맷으로 [Link]를 제거하고 제목에 링크를 거는 방식으로 행사를 등록해볼까 합니다 :)

**Comment by KoEonYack** [comment]
@Limm-jk 

긍정적인 답변 감사합니다 😊

크롤링 스크립트 저장소인 [Dev-Event-Subscribe-Script](https://github.com/brave-people/Dev-Event-Subscribe-Script) 와, issue 등록를 통한 메일링 저장소인 [Dev-Event-Subscribe](https://github.com/brave-people/Dev-Event-Subscribe)에 maintain Role을 드렸습니다!

다음주 정도 서비스 가능하면 좋겠네요! 준비된다면 Dev-Event상단 페이지에 메일링 기능 소개를 추가해야겠어요!

살짝 추가 방안은 이번주 수요일 전까지[Dev-Event-Subscribe-Script](https://github.com/brave-people/Dev-Event-Subscribe-Script)에 issue로 등록해둘께요~!!

앗, 참고로 3월 행사부터는

- __[AI EXPO KOREA 2021](https://event-us.kr/zvKlsXnNkKW6/event/26657)__
  - 분류: `온라인`, `컨퍼런스`, `.NET`
  - 주최: 서울에쎄
  - 일시: 03. 24(수) 10:00 ~ 03. 26(금) 17:00

요런 포맷으로 [Link]를 제거하고 제목에 링크를 거는 방식으로 행사를 등록해볼까 합니다 :)

**Comment by Limm-jk** [comment]
필요한 기능이 있으시다면 편하게 알려주시면 감사하겠습니다!!!

개인적인 생각으로는 Dev-Event-Subscribe-Script를 fork저장소가 아닌 그냥 빈 저장소로 주시면 제가 코드를 수정해가면서 채우는 방향도 좋으리라 생각이 들어요!!

링크는 어차피 href로 링크가 제공이 되니 상관이 없을 것 같습니다. 오히려 더 편할수도 있겠네요 ㅎㅎ

**Comment by KoEonYack** [comment]
@Limm-jk

 Dev-Event-Subscribe-Script 빈저장소로 만들고 maintain Role 권한 드렸습니다~
