### ISSUE TITLE
행사 중복 표시 문제

### ISSUE THREAD

**Issue by kangjung** [brave-people/Dev-Event#201]
2022 Azure Virtual Hackathon에 대한 부분이 중복으로 표시되어 있어 수정이 필요해 보입니다.

![image](https://user-images.githubusercontent.com/28768760/167068058-a035ee4e-4b31-4eab-9327-34f825f9d1d9.png)

**Comment by KoEonYack** [comment]
@kangjung 님 제보 감사합니다~!

해당건 제거 완료하였습니다 👍 💯
