### ISSUE TITLE
7월 오라클 웨비나 링크 잘못 걸림

### ISSUE THREAD

**Issue by NadudAn** [brave-people/Dev-Event#235]
7월 이벤트 **오픈서치 기반 오라클 클라우드의 Search Service 알아보기**의 링크가 **도서리딩 #1 <클론코딩 줌> + 핸즈온랩**으로 되어있습니다. https://www.sharedit.co.kr/seminars/1361여기로 링크 다시 걸어주세요

**Comment by KoEonYack** [comment]
@NadudAn 이슈 감사합니다~ 링크 수정했습니다!
