### ISSUE TITLE
구독형 캘린더로 볼 수 있는 형태 추가

### ISSUE THREAD

**Issue by hmu332233** [brave-people/Dev-Event#332]
안녕하세요!
업데이트해주시는 이벤트들 항상 잘 보고 있습니다. 
사용하다보니 캘린더에서도 바로 볼 수 있으면 좋을 것 같아서

간단하게 만들어봤는데 괜찮으시다면 메일링처럼 공식(?) 기능이면 어떨까 싶어서 제안드립니다.
README 크롤링해서 사용되던 방식들은 조만간 지원이 안될거라고 하셔서 웹 페이지의 api를 이용했습니다.

Repo: https://github.com/hmu332233/Dev-Event-Calendar

### 사용방법
ics 형식을 지원하는 캘린더에 `https://hmu332233.github.io/Dev-Event-Calendar/events.ics` URL로 구독을 추가합니다.

### 적용 모습

<img src="https://user-images.githubusercontent.com/10302969/232250384-206337e3-12b4-4e26-a73a-0dfd8afa0762.png" width="700"/>

**Comment by KoEonYack** [comment]
@hmu332233 님, 

용감한 친구들 관리자 Covnenat입니다. 

데브 이벤트에 관심을 갖어주셔서 감사합니다.

검토 후 답변드리겠습니다.

**Comment by KoEonYack** [comment]
@hmu332233 님,

데브 이벤트에 관심을 가져주셔서 감사합니다. 

다만 본 서비스를 종료해 주시기 바랍니다.

------------------------
### 1. 오픈 API가 아닙니다.
데브 이벤트 웹 서비스는 타 서비스에서 개발자 행사 정보 조회를 위한 오픈 API로 제공하지 않습니다. 

------------------------
### 2. 서비스적으로 교집합 부분이 발생합니다.
현재 웹 & 앱 개선작업을 통하여 유사 서비스를 작업 중에 있습니다. 

조금만 기다려주시면 편리한 방식으로 개발자 행사를 볼 수 있도록 웹&엡 서비스를 개발할 예정입니다. 

------------------------
### 4. 이메일 구독 서비스는 이렇게 다릅니다.
현재 작업주신 캘린더과 이메일 구독 서비스는 이렇게 다릅니다.

1. 이메일 구독 서비스는 데브 이벤트의 API를 사용하지 않고, 1주일에 한번 크롤링 형식으로 이메일 발송합니다.
2. 직접 이메일 발송을 서버에서 구현하면 발송에 따른 비용이 발생합니다. 그러나 Github issue 등록 방식을 통한 이메일 발송이기에 비용이 발생하지 않습니다. 이에 대한 임팩트가 커서 허가한 서비스입니다. 

------------------------
### 5. API 호출을 막을 예정입니다.

이 계기로 서버 로그를 조회했을 때 최근에도 허용하지 않은 클라이언트에서 API 호출이 발생하고 있는 것을 발견하였습니다. 

빠른 시일 내로 IP 차단, 양방 키를 이용한 암호화 API 통신을 적용하겠습니다.

API 호출이 계속 가능하다 하더라도 사용을 허가한 것은 아닙니다. 

------------------------
### 6. 향후 데브 이벤트를 개선을 위해서 보시는 분들을 위하여 

혹시나 서비스 제안을 위하여 요청 주시는 분들을 위하여 추가로 글 남깁니다. 

지금까지 데브 이벤트의 정보를 이용하기 위해서 선 제안 후 검토 후 개발 요청으로 진행하고 있습니다.

다만 이 과정을 건너뛰고 서비스화하는 것은 원치 않습니다.

**Comment by hmu332233** [comment]
@KoEonYack 

안녕하세요. 답변 감사합니다!
약간의 오해가 있을 것 같아 몇가지 말씀드리자면

> 다만 본 서비스를 종료해 주시기 바랍니다.

서비스를 하려고 만든 것은 아니고 어디까지나 제안을 하기 위해서 만들어진 프로젝트입니다.
말씀해주신대로 여기서 사용되지 않는다면 닫을 예정입니다.

어디까지나 데브 이벤트의 기능의 일환으로 제공이되는 것을 목적으로 했던거라서요.

> 이메일 구독 서비스는 이렇게 다릅니다.

제안드린 방향도 API를 직접 사용하긴하지만 매번 사용하지는 않으며
크롤링 대신 주기에 따라 1회만 호출하게 됩니다.

대신 캘린더 이벤트를 위한 데이터를 Github에 저장하고, 이를 Github Page 기능을 이용하여 API 형식으로 제공함으로써 
트래픽은 모두 Github이 감당하는 방식이였습니다.

---

제안에 대해서 적극적으로 검토해주셔서 감사합니다! 🙇🙇

API를 허가 없이 사용하여 서비스를 구현한 것처럼 비춰져서 좀 걸리긴합니다만..
이 부분에 오해가 있으셨다면 해결되었으면하고

서비스에 보안적 기여를 했다고 생각하고 이번 이슈는 확인하시는대로 닫겠습니다.
이번 이슈는 내용을 정리하여, 다른 이슈를 작성하여 고정시켜두는 것도 좋을 것 같네요.
