### ISSUE TITLE
오월엔 데브콘 in DAEJEON 링크 잘못 걸림

### ISSUE THREAD

**Issue by hyur777** [brave-people/Dev-Event#350]
[오월엔 데브콘 in DAEJEON](https://festa.io/events/3430)

해당 링크로 이동하면 [Flutter in Songdo 맥주파티!](https://festa.io/events/3430)로 이동됩니다

https://festa.io/events/3467 링크로 수정해주시면 될 것 같습니다.

**Comment by KoEonYack** [comment]
@hyur777 님 수정 완료하였습니다. 감사합니다 👍 💯
