### ISSUE TITLE
행사 중복 표시 문제

### ISSUE THREAD

**Issue by kangjung** [brave-people/Dev-Event#375]
I/O Extended 2023 Seoul 행사가 중복으로 표시되어 있어 수정이 필요해 보입니다.

![image](https://github.com/brave-people/Dev-Event/assets/28768760/4aeb1f16-0a10-4789-b986-16350a99ec70)

**Comment by KoEonYack** [comment]
@kangjung 님 중복행사 제거하였습니다. 제보 감사합니다 👍 💯
