### ISSUE TITLE
한빛N MSA - #3 Code Review 의 링크가 잘못 설정되어 있습니다 ~

### ISSUE THREAD

**Issue by jhk0530** [brave-people/Dev-Event#391]
아래의 google cloud next로 링크가 설정 되어 있어요 ~

원래 링크 https://festa.io/events/3819로 바꿔서 다시 올리면 될까요?

**Comment by KoEonYack** [comment]
@jhk0530 님~ 

Issue 감사합니다.

마침 PR 주셔서 PR에 수정사항 반영해서 머지하였습니다.

감사합니다^^
