### ISSUE TITLE
MEDICAL HACK 2023 링크 오류

### ISSUE THREAD

**Issue by kangjung** [brave-people/Dev-Event#405]
MEDICAL HACK 2023 행사의 링크가 UNITY APAC INDUSTRY SUMMIT 2023 링크로 잘못 지정되어있습니다.

**Comment by KoEonYack** [comment]
@kangjung 님 수정 커밋하였습니다.

데브 이벤트에 관심을 갖어주셔서 감사합니다 👍 💯
