### ISSUE TITLE
행사중복 표시

### ISSUE THREAD

**Issue by kangjung** [brave-people/Dev-Event#420]
EOST2023 행사에 대해서 접수일로 표시된 내용과 일시로 표시된 내용이 중복으로 있습니다.
![image](https://github.com/brave-people/Dev-Event/assets/28768760/24416ed2-99ac-444a-8298-c7b4f79d43e8)
접수일로 안내된 링크에서는 홈페이지로 링크가 걸려있고,
![image](https://github.com/brave-people/Dev-Event/assets/28768760/2913b186-4b3a-4db9-95cb-aab1ab244ec4)
일시로 안내된 링크는 온오프믹스로 연결되어있네요.

중복으로 적힌 행사에 대한 정리가 필요할것 같습니다.

**Comment by KoEonYack** [comment]
안녕하세요!

중복 행사는 제거하였습니다. 

감사합니다 👍 💯
