### ISSUE TITLE
iamroot 추가

### ISSUE THREAD

**Issue by paranlee** [brave-people/Dev-Event#438]
최근에도 활발한 활동을 이어나가는 리눅스 커널 스터디 그룹 iamroot 링크 추가가 필요합니다.
- http://www.iamroot.org/xe/

**Comment by KoEonYack** [comment]
@paranlee 님 추가 완료하였습니다! 감사합니다 👍 💯

**Comment by paranlee** [comment]
네 확인했습니다. 추가해주셔서 감사합니다!
