### ISSUE TITLE
행사중복 표시

### ISSUE THREAD

**Issue by kangjung** [brave-people/Dev-Event#460]
Devfest Songdo 2023 행사가 중복으로 표시되고 있습니다.

![image](https://github.com/brave-people/Dev-Event/assets/28768760/0ce05b4c-99a7-4cae-851d-530c5b75dac2)

**Comment by KoEonYack** [comment]
@kangjung 님 감사합니다. https://github.com/brave-people/Dev-Event/commit/de82d028ae798be6e928757c3260be574a9db82e 에서 반영하였습니다. 👍 💯
