### ISSUE TITLE
알고리즘 캠프 링크 오류

### ISSUE THREAD

**Issue by dgh06175** [brave-people/Dev-Event#469]
개발 교육 탭에 알고리즘 캠프 링크 접속이 불가합니다.
https://algorithmcamp.oopy.io/

**Comment by JinleeJeong** [comment]
[회고모임은 하고 싶은데 어디에도 끼기 애매한 사람을 위한 송년회](https://festa.io/events/4475)

해당 링크도 접속이 불가합니다.

**Comment by KoEonYack** [comment]
@JinleeJeong 님

> 개발 교육 탭에 알고리즘 캠프 링크 접속이 불가합니다.

유튜버 컴공선배의 알고리즘 캠프입니다. 확인해보니 링크가 변경되었네요.
https://neordinary.co.kr/sub/rc.php 

다만 강의 가격이 고가이기에 dev event 성격과 맞지 않아 해당 부분은 제외처리하겠습니다 :)

**Comment by KoEonYack** [comment]
@JinleeJeong 

> 회고모임은 하고 싶은데 어디에도 끼기 애매한 사람을 위한 송년회

https://festa.io/hosts/2259 가 주최자이신데 행사를 삭제하셨네요^^

역시 해당 행사도 제외처리 하겠습니다. 

감사합니다 :)

**Comment by KoEonYack** [comment]
https://github.com/brave-people/Dev-Event/commit/8f458a675f259f493f686b00274fef488bf05c4e 커밋하였습니다. 감사합니다!
