### ISSUE TITLE
페이지를 찾을 수 없음

### ISSUE THREAD

**Issue by kimgh06** [brave-people/Dev-Event#498]
![image](https://github.com/brave-people/Dev-Event/assets/101877146/8813a09e-42b7-44b4-ac15-150503779bdb)

**Comment by KoEonYack** [comment]
@kimgh06 님

클라우드 이관 작업으로 현재 서비스가 원활하지 않습니다. 

개선하여 서비스를 이용할 수 있도록 준비하겠습니다!

**Comment by KoEonYack** [comment]
@kimgh06 님

서비스 재오픈 완료하였습니다~
