### ISSUE TITLE
Bug : Dev Event 웹 - 각 행사들에 대한 링크가 하나씩 밀려있습니다

### ISSUE THREAD

**Issue by sungpaks** [brave-people/Dev-Event#504]
![image](https://github.com/brave-people/Dev-Event/assets/122661764/54204b61-8d7e-4574-8702-9499b983db84)
"AWSKRUG 서버리스 #serverless 모임" 행사에 마우스 호버한 화면입니다. 바로 위에 위치한 크래프론  6기에 해당하는 URL로 등록되어 있습니다.
동일하게, Dev Event 웹의 각 행사들을 클릭하면 해당 행사의 바로 위에 있는 행사로 연결되어 있습니다
모바일(iPhone) 크롬에서 접속해도 동일하고,
날짜나 태그를 건드린 후에는 정상적으로 URL이 연결되어 있습니다

**Comment by KoEonYack** [comment]
@sungpaks 님~

오류 리포트 감사합니다. 

우선은 알려진 이슈인데요! 제 환경에서 확인하였을때는 정상으로 나옵니다.

날짜와 태그는 선택하지 않고 바로 접속했을때입니다. 

<img width="1047" alt="스크린샷 2024-04-15 오후 11 34 49" src="https://github.com/brave-people/Dev-Event/assets/28642484/41b7743f-c700-4a58-ba95-c567ed945846">

전면 개편이 미루어지면서 해당 이슈를 해결하지 못한 상태입니다..

개편 진행할때 해당 부분 이슈 발생할지 확인하며 진행하겠습니다.

감사합니다
