### ISSUE TITLE
크롤링을 이용한 앱 제작 문의

### ISSUE THREAD

**Issue by jisungbin** [brave-people/Dev-Event#78]
**안녕하세요, 우선 좋은 레포를 만들어주셔서 감사합니다 :)**

저도 컨퍼런스에 참여하기 원하는 한 개발자로서, 이 레포에 종종 들려 새로운 컨퍼런스가 있는지 확인을 하곤 합니다.
하지만 매번 확인하러 이 레포까지 오는 게 번거롭다고 느껴져서 우리가 항상 소지하고 다니는
핸드폰의 앱으로 만들면 좋을 거 같아서 제작해보려고 합니다.

`Android`와 `iOS` 모두 제작 가능하며, 이 레포를 크롤링하는 식으로 정보를 수집하여 앱을 만들려고 하는데
크롤링을 진행하여 이 레포를 기반으로 한 앱을 만들어도 될까요?

**Comment by KoEonYack** [comment]
@jisungbin 님, 안녕하세요!!

좋은 제안 감사합니다! 긍정적으로 생각하고요,

몇가지 궁금한점이 있어서 정리해서 오늘, 내일중으로 다시 comment 남기겠습니다!

**Comment by KoEonYack** [comment]
@jisungbin 안녕하세요!

우선 앱개발을 해주신다는 것에 깊은 감사를 드립니다! README로 제공하는것에 한계를 느끼고 있습니다^^,,

> 용감한 친구들 Organization 소속으로 오셔서 앱 개발이 가능하실까요?

용감한 친구들은, 대학생 친구들과 만들었지만 현재는 다양한 소속의 분들이 있습니다. [brave-people](https://github.com/brave-people)  작업하시는거 자유롭게 개발하시면 되겠습니다!

용감한 친구들 이름으로 앱 홍보가 가능하며 Dev Event는 웹 버전을 준비중입니다.(예상은 9월 초이지만 언제든 밀릴 수 있습니다.) 웹 버전 공개 이후 3개월 README로 병행 운영할 예정입니다. 제가 앱 개발자와 협업한 적은 없기에 웹 버전을 준비하면서 API 스팩에 대해서 궁금한 부분도 질문드리고, 작업하시는거 보면서 자극도 받고 좋을것 같습니다.

사용하시는 개발자 계정으로 스토어에 올리시면 되고, 좋은 포트폴리오가 되겠네요!

**Comment by jisungbin** [comment]
@KoEonYack 안녕하세요!
긍정적으로 봐주신 것과, 답변 감사합니다 😄 

> 용감한 친구들 Organization 소속으로 들어가서 앱 개발 하고 싶습니다!

좋은 제안해주셔서 다시 한 번 감사합니다 :)

용친 소속이 되기 위해 제가 추가적으로 제공해야 하는 정보가 있을까요?

**Comment by KoEonYack** [comment]
@jisungbin 감사합니다 :)

그룹 가입 메일을 보냈습니다!

**Comment by jisungbin** [comment]
@KoEonYack 그룹 가입 하였습니다! 감사합니다!!
열심히 작업해보겠습니다 :)

**Comment by KoEonYack** [comment]
@jisungbin 감사합니다!

하시다가 혹시 궁금한 부분이 있다면 언제든 issue 남겨주세요!

평안한밤 되세요 :)
